export const wine = {
    "mention": [
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0150000/W0150974.jpg",
            "wineName": "다다",
            "wineNameEng": "DADA",
            "wineType": "스파클링",
            "wineMention": 18,
            "winePrice": 0,
            "wineSweet": 4,
            "wineBody": 2,
            "wineVariety": "소비뇽 블랑",
            "aroma1": "꽃",
            "aroma2": "사과",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0160000/W0160819.jpg",
            "wineName": "도스",
            "wineNameEng": "Dos",
            "wineType": "레드",
            "wineMention": 13,
            "winePrice": 4,
            "wineSweet": 1,
            "wineBody": 4,
            "wineVariety": "블렌디드",
            "aroma1": "베리",
            "aroma2": "시나몬",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0165000/W0165535.jpg",
            "wineName": "아트",
            "wineNameEng": "Art",
            "wineType": "레드",
            "wineMention": 7,
            "winePrice": 9,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "멘시아",
            "aroma1": "돌",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158537.jpg",
            "wineName": "미래",
            "wineNameEng": "Mirre",
            "wineType": "레드",
            "wineMention": 7,
            "winePrice": 8,
            "wineSweet": 1,
            "wineBody": 4,
            "wineVariety": "네그로아마로",
            "aroma1": "베리",
            "aroma2": "사과",
            "aroma3": "숙성"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0161000/W0161738.jpg",
            "wineName": "네스폴리 르 코스테",
            "wineNameEng": "Poderi dal Nespoli Le Coste",
            "wineType": "화이트",
            "wineMention": 5,
            "winePrice": 3,
            "wineSweet": 1,
            "wineBody": 2,
            "wineVariety": "블렌디드",
            "aroma1": "레몬",
            "aroma2": "사과",
            "aroma3": " "
        }
    ],
    "access": [
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0150000/W0150974.jpg",
            "wineName": "다다",
            "wineNameEng": "DADA",
            "wineType": "스파클링",
            "wineMention": 18,
            "winePrice": 0,
            "wineSweet": 4,
            "wineBody": 2,
            "wineVariety": "소비뇽 블랑",
            "aroma1": "꽃",
            "aroma2": "사과",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158537.jpg",
            "wineName": "미래",
            "wineNameEng": "Mirre",
            "wineType": "레드",
            "wineMention": 7,
            "winePrice": 8,
            "wineSweet": 1,
            "wineBody": 4,
            "wineVariety": "네그로아마로",
            "aroma1": "베리",
            "aroma2": "사과",
            "aroma3": "숙성"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0169000/W0169071.png",
            "wineName": "퓨메 도오로",
            "wineNameEng": "Fiume D'Oro",
            "wineType": "화이트",
            "wineMention": 1,
            "winePrice": 4,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "블렌드",
            "aroma1": "돌",
            "aroma2": "허브",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0167000/W0167472.png",
            "wineName": "도스 코파스 리제르바",
            "wineNameEng": "Dos Copas Reserva",
            "wineType": "레드",
            "wineMention": 1,
            "winePrice": 0,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "블렌디드",
            "aroma1": "꽃",
            "aroma2": "베리",
            "aroma3": "사과"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0166000/W0166123.jpg",
            "wineName": "도스 코파스 레드 블렌드",
            "wineNameEng": "Dos Copas Red Blend",
            "wineType": "레드",
            "wineMention": 1,
            "winePrice": 0,
            "wineSweet": 2,
            "wineBody": 3,
            "wineVariety": "블렌디드",
            "aroma1": "베리",
            "aroma2": "사과",
            "aroma3": " "
        }
    ],
    "present": [
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0150000/W0150974.jpg",
            "wineName": "다다",
            "wineNameEng": "DADA",
            "wineType": "스파클링",
            "wineMention": 18,
            "winePrice": 0,
            "wineSweet": 4,
            "wineBody": 2,
            "wineVariety": "소비뇽 블랑",
            "aroma1": "꽃",
            "aroma2": "사과",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0160000/W0160819.jpg",
            "wineName": "도스",
            "wineNameEng": "Dos",
            "wineType": "레드",
            "wineMention": 13,
            "winePrice": 4,
            "wineSweet": 1,
            "wineBody": 4,
            "wineVariety": "블렌디드",
            "aroma1": "베리",
            "aroma2": "시나몬",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0161000/W0161738.jpg",
            "wineName": "네스폴리 르 코스테",
            "wineNameEng": "Poderi dal Nespoli Le Coste",
            "wineType": "화이트",
            "wineMention": 5,
            "winePrice": 3,
            "wineSweet": 1,
            "wineBody": 2,
            "wineVariety": "블렌디드",
            "aroma1": "레몬",
            "aroma2": "사과",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158537.jpg",
            "wineName": "미래",
            "wineNameEng": "Mirre",
            "wineType": "레드",
            "wineMention": 7,
            "winePrice": 8,
            "wineSweet": 1,
            "wineBody": 4,
            "wineVariety": "네그로아마로",
            "aroma1": "베리",
            "aroma2": "사과",
            "aroma3": "숙성"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0165000/W0165535.jpg",
            "wineName": "아트",
            "wineNameEng": "Art",
            "wineType": "레드",
            "wineMention": 7,
            "winePrice": 9,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "멘시아",
            "aroma1": "돌",
            "aroma2": " ",
            "aroma3": " "
        }
    ],
    "price": [
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0167000/W0167039.jpg",
            "wineName": "도스 코파스 샤르도네",
            "wineNameEng": "Dos Copas Chardonnay",
            "wineType": "화이트",
            "wineMention": 1,
            "winePrice": 0,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "샤르도네",
            "aroma1": "사과",
            "aroma2": "파인애플",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0166000/W0166123.jpg",
            "wineName": "도스 코파스 레드 블렌드",
            "wineNameEng": "Dos Copas Red Blend",
            "wineType": "레드",
            "wineMention": 1,
            "winePrice": 0,
            "wineSweet": 2,
            "wineBody": 3,
            "wineVariety": "블렌디드",
            "aroma1": "베리",
            "aroma2": "사과",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158836.jpg",
            "wineName": "버디",
            "wineNameEng": "Buddy",
            "wineType": "스파클링",
            "wineMention": 2,
            "winePrice": 0,
            "wineSweet": 4,
            "wineBody": 5,
            "wineVariety": "모스카토",
            "aroma1": "꽃",
            "aroma2": "사과",
            "aroma3": "파인애플"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0150000/W0150974.jpg",
            "wineName": "다다",
            "wineNameEng": "DADA",
            "wineType": "스파클링",
            "wineMention": 18,
            "winePrice": 0,
            "wineSweet": 4,
            "wineBody": 2,
            "wineVariety": "소비뇽 블랑",
            "aroma1": "꽃",
            "aroma2": "사과",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0167000/W0167472.png",
            "wineName": "도스 코파스 리제르바",
            "wineNameEng": "Dos Copas Reserva",
            "wineType": "레드",
            "wineMention": 1,
            "winePrice": 0,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "블렌디드",
            "aroma1": "꽃",
            "aroma2": "베리",
            "aroma3": "사과"
        }
    ]
}