export const wine = {
  "mention": [
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0150000/W0150974.jpg",
          "다다",
          "DADA",
          "스파클링",
          18,
          0,
          4,
          2,
          "소비뇽 블랑",
          "꽃",
          "사과",
          " "
      ],
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0160000/W0160819.jpg",
          "도스",
          "Dos",
          "레드",
          13,
          4,
          1,
          4,
          "블렌디드",
          "베리",
          "시나몬",
          " "
      ],
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0165000/W0165535.jpg",
          "아트",
          "Art",
          "레드",
          7,
          9,
          1,
          3,
          "멘시아",
          "돌",
          " ",
          " "
      ],
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158537.jpg",
          "미래",
          "Mirre",
          "레드",
          7,
          8,
          1,
          4,
          "네그로아마로",
          "베리",
          "사과",
          "숙성"
      ],
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0161000/W0161738.jpg",
          "네스폴리 르 코스테",
          "Poderi dal Nespoli Le Coste",
          "화이트",
          5,
          3,
          1,
          2,
          "블렌디드",
          "레몬",
          "사과",
          " "
      ]
  ],
  "access": [
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0150000/W0150974.jpg",
          "다다",
          "DADA",
          "스파클링",
          18,
          0,
          4,
          2,
          "소비뇽 블랑",
          "꽃",
          "사과",
          " "
      ],
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158537.jpg",
          "미래",
          "Mirre",
          "레드",
          7,
          8,
          1,
          4,
          "네그로아마로",
          "베리",
          "사과",
          "숙성"
      ],
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0169000/W0169071.png",
          "퓨메 도오로",
          "Fiume D'Oro",
          "화이트",
          1,
          4,
          1,
          3,
          "블렌드",
          "돌",
          "허브",
          " "
      ],
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0167000/W0167472.png",
          "도스 코파스 리제르바",
          "Dos Copas Reserva",
          "레드",
          1,
          0,
          1,
          3,
          "블렌디드",
          "꽃",
          "베리",
          "사과"
      ],
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0166000/W0166123.jpg",
          "도스 코파스 레드 블렌드",
          "Dos Copas Red Blend",
          "레드",
          1,
          0,
          2,
          3,
          "블렌디드",
          "베리",
          "사과",
          " "
      ]
  ],
  "present": [
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0150000/W0150974.jpg",
          "다다",
          "DADA",
          "스파클링",
          18,
          0,
          4,
          2,
          "소비뇽 블랑",
          "꽃",
          "사과",
          " "
      ],
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0160000/W0160819.jpg",
          "도스",
          "Dos",
          "레드",
          13,
          4,
          1,
          4,
          "블렌디드",
          "베리",
          "시나몬",
          " "
      ],
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0161000/W0161738.jpg",
          "네스폴리 르 코스테",
          "Poderi dal Nespoli Le Coste",
          "화이트",
          5,
          3,
          1,
          2,
          "블렌디드",
          "레몬",
          "사과",
          " "
      ],
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158537.jpg",
          "미래",
          "Mirre",
          "레드",
          7,
          8,
          1,
          4,
          "네그로아마로",
          "베리",
          "사과",
          "숙성"
      ],
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0165000/W0165535.jpg",
          "아트",
          "Art",
          "레드",
          7,
          9,
          1,
          3,
          "멘시아",
          "돌",
          " ",
          " "
      ]
  ],
  "price": [
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0167000/W0167472.png",
          "도스 코파스 리제르바",
          "Dos Copas Reserva",
          "레드",
          1,
          0,
          1,
          3,
          "블렌디드",
          "꽃",
          "베리",
          "사과"
      ],
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0150000/W0150974.jpg",
          "다다",
          "DADA",
          "스파클링",
          18,
          0,
          4,
          2,
          "소비뇽 블랑",
          "꽃",
          "사과",
          " "
      ],
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0166000/W0166123.jpg",
          "도스 코파스 레드 블렌드",
          "Dos Copas Red Blend",
          "레드",
          1,
          0,
          2,
          3,
          "블렌디드",
          "베리",
          "사과",
          " "
      ],
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158836.jpg",
          "버디",
          "Buddy",
          "스파클링",
          2,
          0,
          4,
          5,
          "모스카토",
          "꽃",
          "사과",
          "파인애플"
      ],
      [
          "https://wine21.speedgabia.com/WINE_MST/TITLE/0167000/W0167039.jpg",
          "도스 코파스 샤르도네",
          "Dos Copas Chardonnay",
          "화이트",
          1,
          0,
          1,
          3,
          "샤르도네",
          "사과",
          "파인애플",
          " "
      ]
  ]
}