export const recent_wine = [
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0168000/W0168328.png",
        "wineName": "파운",
        "wineNameEng": "Faune",
        "wineType": "화이트",
        "winePrice": 5,
        "wineSweet": 1,
        "wineBody": 3,
        "wineVariety": "블렌디드",
        "aroma1": "꽃",
        "aroma2": "돌",
        "aroma3": "사과"
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0169000/W0169070.png",
        "wineName": "넛뜨 비올라",
        "wineNameEng": "Notte Viola",
        "wineType": "레드",
        "winePrice": 4,
        "wineSweet": 1,
        "wineBody": 3,
        "wineVariety": "블렌드",
        "aroma1": "시나몬",
        "aroma2": "오크통",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0165000/W0165535.jpg",
        "wineName": "아트",
        "wineNameEng": "Art",
        "wineType": "레드",
        "winePrice": 9,
        "wineSweet": 1,
        "wineBody": 3,
        "wineVariety": "멘시아",
        "aroma1": "돌",
        "aroma2": " ",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0161000/W0161738.jpg",
        "wineName": "네스폴리 르 코스테",
        "wineNameEng": "Poderi dal Nespoli Le Coste",
        "wineType": "화이트",
        "winePrice": 3,
        "wineSweet": 1,
        "wineBody": 2,
        "wineVariety": "블렌디드",
        "aroma1": "레몬",
        "aroma2": "사과",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0165000/W0165598.jpg",
        "wineName": "피플",
        "wineNameEng": "People",
        "wineType": "화이트",
        "winePrice": 3,
        "wineSweet": 2,
        "wineBody": 2,
        "wineVariety": "블렌디드",
        "aroma1": "꽃",
        "aroma2": "사과",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158836.jpg",
        "wineName": "버디",
        "wineNameEng": "Buddy",
        "wineType": "스파클링",
        "winePrice": 0,
        "wineSweet": 4,
        "wineBody": 5,
        "wineVariety": "모스카토",
        "aroma1": "꽃",
        "aroma2": "사과",
        "aroma3": "파인애플"
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0150000/W0150974.jpg",
        "wineName": "다다",
        "wineNameEng": "DADA",
        "wineType": "스파클링",
        "winePrice": 0,
        "wineSweet": 4,
        "wineBody": 2,
        "wineVariety": "소비뇽 블랑",
        "aroma1": "꽃",
        "aroma2": "사과",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0165000/W0165524.jpg",
        "wineName": "시크 바르셀로나 브뤼",
        "wineNameEng": "Chic Barcelona Brut",
        "wineType": "스파클링",
        "winePrice": 4,
        "wineSweet": 1,
        "wineBody": 2,
        "wineVariety": "블렌디드",
        "aroma1": "레몬",
        "aroma2": "사과",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0141000/W0141387.jpg",
        "wineName": "빌라 엠",
        "wineNameEng": "Villa M",
        "wineType": "화이트",
        "winePrice": 3,
        "wineSweet": 4,
        "wineBody": 2,
        "wineVariety": "모스카토",
        "aroma1": "파인애플",
        "aroma2": " ",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0154000/W0154020.jpg",
        "wineName": "간치아 모스카토 로제",
        "wineNameEng": "Gancia Moscato Rose",
        "wineType": "스파클링",
        "winePrice": 3,
        "wineSweet": 4,
        "wineBody": 2,
        "wineVariety": "블렌디드",
        "aroma1": "꽃",
        "aroma2": "레몬",
        "aroma3": "베리"
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0153000/W0153507.jpg",
        "wineName": "샤또 데스클랑",
        "wineNameEng": "Chateau d'Esclans",
        "wineType": "로제",
        "winePrice": 8,
        "wineSweet": 1,
        "wineBody": 3,
        "wineVariety": "블렌디드",
        "aroma1": "레몬",
        "aroma2": "베리",
        "aroma3": "사과"
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0157000/W0157179.jpg",
        "wineName": "한 메를로",
        "wineNameEng": "Hahn Merlot",
        "wineType": "레드",
        "winePrice": 5,
        "wineSweet": 1,
        "wineBody": 3,
        "wineVariety": "블렌디드",
        "aroma1": "베리",
        "aroma2": "오크통",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0160000/W0160819.jpg",
        "wineName": "도스",
        "wineNameEng": "Dos",
        "wineType": "레드",
        "winePrice": 4,
        "wineSweet": 1,
        "wineBody": 4,
        "wineVariety": "블렌디드",
        "aroma1": "베리",
        "aroma2": "시나몬",
        "aroma3": " "
    }
]