export const recent_wine = [
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0154000/T0154071_001.png",
        "wineName": "또스띠 핑크 모스카토",
        "wineNameEng": "Tosti Pink Moscato",
        "wineType": "스파클링",
        "winePrice": 2,
        "wineSweet": 4,
        "wineBody": 3,
        "wineVariety": "블렌디드",
        "aroma1": "꽃",
        "aroma2": "베리",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0160000/W0160819.jpg",
        "wineName": "도스",
        "wineNameEng": "Dos",
        "wineType": "레드",
        "winePrice": 4,
        "wineSweet": 1,
        "wineBody": 4,
        "wineVariety": "블렌디드",
        "aroma1": "베리",
        "aroma2": "시나몬",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0139000/139852.jpg",
        "wineName": "닥터 루젠 리슬링",
        "wineNameEng": "Dr.Loosen Riesling",
        "wineType": "화이트",
        "winePrice": 4,
        "wineSweet": 3,
        "wineBody": 2,
        "wineVariety": "리슬링",
        "aroma1": "돌",
        "aroma2": "사과",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0162000/T0162697_002.png",
        "wineName": "까스따뇨 로제 세미 스위트",
        "wineNameEng": "Castano Rose Semi Sweet",
        "wineType": "로제",
        "winePrice": 3,
        "wineSweet": 3,
        "wineBody": 2,
        "wineVariety": "모나스트렐",
        "aroma1": "베리",
        "aroma2": " ",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0150000/W0150974.jpg",
        "wineName": "다다",
        "wineNameEng": "DADA",
        "wineType": "스파클링",
        "winePrice": 0,
        "wineSweet": 4,
        "wineBody": 2,
        "wineVariety": "소비뇽 블랑",
        "aroma1": "꽃",
        "aroma2": "사과",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0166000/W0166667.jpg",
        "wineName": "프로메사",
        "wineNameEng": "Promesa",
        "wineType": "레드",
        "winePrice": 4,
        "wineSweet": 1,
        "wineBody": 4,
        "wineVariety": "블렌디드",
        "aroma1": "말린과일",
        "aroma2": "베리",
        "aroma3": "시나몬"
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0140000/W0140169.jpg",
        "wineName": "빌라 욜란다 모스카토 다스티",
        "wineNameEng": "Villa Jolanda Moscato d'Asti",
        "wineType": "화이트",
        "winePrice": 3,
        "wineSweet": 4,
        "wineBody": 2,
        "wineVariety": "모스카토",
        "aroma1": "꽃",
        "aroma2": "레몬",
        "aroma3": "사과"
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0137000/W0137444.jpg",
        "wineName": "트라피체 싱글 빈야드 말벡",
        "wineNameEng": "Trapiche Single Vineyard Malbec",
        "wineType": "레드",
        "winePrice": 10,
        "wineSweet": 1,
        "wineBody": 4,
        "wineVariety": "말벡",
        "aroma1": "꽃",
        "aroma2": "사과",
        "aroma3": "숙성"
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158537.jpg",
        "wineName": "미래",
        "wineNameEng": "Mirre",
        "wineType": "레드",
        "winePrice": 8,
        "wineSweet": 1,
        "wineBody": 4,
        "wineVariety": "네그로아마로",
        "aroma1": "베리",
        "aroma2": "사과",
        "aroma3": "숙성"
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0161000/W0161301.png",
        "wineName": "빌라 욜란다 모스카토 로제",
        "wineNameEng": "Villa Jolanda Moscato Rose",
        "wineType": "스파클링",
        "winePrice": 3,
        "wineSweet": 4,
        "wineBody": 3,
        "wineVariety": "블렌디드",
        "aroma1": "말린과일",
        "aroma2": "베리",
        "aroma3": "사과"
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0159000/W0159214.jpg",
        "wineName": "골든 스파이럴 아이스",
        "wineNameEng": "Golden Spiral Ice",
        "wineType": "화이트",
        "winePrice": 6,
        "wineSweet": 5,
        "wineBody": 4,
        "wineVariety": "블렌디드",
        "aroma1": "사과",
        "aroma2": "숙성",
        "aroma3": "파인애플"
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0164000/W0164501.jpg",
        "wineName": "슈미트 숀 돈펠더 라인헤센",
        "wineNameEng": "Schmitt Sohne Dornfelder Rheinhessen",
        "wineType": "레드",
        "winePrice": 2,
        "wineSweet": 3,
        "wineBody": 2,
        "wineVariety": "돈펠더",
        "aroma1": "꽃",
        "aroma2": " ",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0168000/W0168577.png",
        "wineName": "아리온 마마망고",
        "wineNameEng": "Arione Mama mango",
        "wineType": "스파클링",
        "winePrice": 3,
        "wineSweet": 3,
        "wineBody": 1,
        "wineVariety": "블렌드",
        "aroma1": "레몬",
        "aroma2": "파인애플",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0168000/T0168631_001.png",
        "wineName": "에스 쿠이코 오크드 샤도네이",
        "wineNameEng": "Es Cuiko Oaked Chardonnay",
        "wineType": "화이트",
        "winePrice": 6,
        "wineSweet": 1,
        "wineBody": 2,
        "wineVariety": "샤르도네",
        "aroma1": "사과",
        "aroma2": "시나몬",
        "aroma3": "오크통"
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0146000/W0146981.jpg",
        "wineName": "발레벨보 브라께또",
        "wineNameEng": "Vallebelbo Brachetto",
        "wineType": "스파클링",
        "winePrice": 2,
        "wineSweet": 4,
        "wineBody": 2,
        "wineVariety": "브라케토",
        "aroma1": "꽃",
        "aroma2": "사과",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0160000/W0160001.jpg",
        "wineName": "피치니 키안티",
        "wineNameEng": "Piccini Chianti",
        "wineType": "레드",
        "winePrice": 1,
        "wineSweet": 1,
        "wineBody": 3,
        "wineVariety": "블렌디드",
        "aroma1": "레몬",
        "aroma2": " ",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0157000/T0157182_006.png",
        "wineName": "한 피노누아",
        "wineNameEng": "Hahn Pinot Noir",
        "wineType": "레드",
        "winePrice": 6,
        "wineSweet": 1,
        "wineBody": 2,
        "wineVariety": "피노 누아",
        "aroma1": "베리",
        "aroma2": "사과",
        "aroma3": "숙성"
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0165000/W0165535.jpg",
        "wineName": "아트",
        "wineNameEng": "Art",
        "wineType": "레드",
        "winePrice": 9,
        "wineSweet": 1,
        "wineBody": 3,
        "wineVariety": "멘시아",
        "aroma1": "돌",
        "aroma2": " ",
        "aroma3": " "
    }
]