export const recent_wine = [
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0160000/W0160819.jpg",
        "wineName": "도스",
        "wineNameEng": "Dos",
        "wineType": "레드",
        "winePrice": 4,
        "wineSweet": 1,
        "wineBody": 4,
        "wineVariety": "블렌디드",
        "aroma1": "베리",
        "aroma2": "시나몬",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0161000/W0161247.jpg",
        "wineName": "발타사르 가르나차",
        "wineNameEng": "Baltasar Garnacha",
        "wineType": "레드",
        "winePrice": 4,
        "wineSweet": 1,
        "wineBody": 3,
        "wineVariety": "가르나차",
        "aroma1": "베리",
        "aroma2": " ",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0161000/W0161738.jpg",
        "wineName": "네스폴리 르 코스테",
        "wineNameEng": "Poderi dal Nespoli Le Coste",
        "wineType": "화이트",
        "winePrice": 3,
        "wineSweet": 1,
        "wineBody": 2,
        "wineVariety": "블렌디드",
        "aroma1": "레몬",
        "aroma2": "사과",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158836.jpg",
        "wineName": "버디",
        "wineNameEng": "Buddy",
        "wineType": "스파클링",
        "winePrice": 0,
        "wineSweet": 4,
        "wineBody": 5,
        "wineVariety": "모스카토",
        "aroma1": "꽃",
        "aroma2": "사과",
        "aroma3": "파인애플"
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158537.jpg",
        "wineName": "미래",
        "wineNameEng": "Mirre",
        "wineType": "레드",
        "winePrice": 8,
        "wineSweet": 1,
        "wineBody": 4,
        "wineVariety": "네그로아마로",
        "aroma1": "베리",
        "aroma2": "사과",
        "aroma3": "숙성"
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0165000/W0165535.jpg",
        "wineName": "아트",
        "wineNameEng": "Art",
        "wineType": "레드",
        "winePrice": 9,
        "wineSweet": 1,
        "wineBody": 3,
        "wineVariety": "멘시아",
        "aroma1": "돌",
        "aroma2": " ",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0137000/W0137502.png",
        "wineName": "발비 소프라니 아스티",
        "wineNameEng": "Balbi Soprani Asti",
        "wineType": "스파클링",
        "winePrice": 4,
        "wineSweet": 4,
        "wineBody": 2,
        "wineVariety": "모스카토",
        "aroma1": "꽃",
        "aroma2": "레몬",
        "aroma3": "사과"
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0142000/T0142219_003.png",
        "wineName": "타라파카 그란 레세르바 까베르네 소비뇽",
        "wineNameEng": "Tarapaca Gran Reserva Cabernet Sauvignon",
        "wineType": "레드",
        "winePrice": 6,
        "wineSweet": 1,
        "wineBody": 4,
        "wineVariety": "카베르네 소비뇽",
        "aroma1": "베리",
        "aroma2": "사과",
        "aroma3": "시나몬"
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0169000/W0169071.png",
        "wineName": "퓨메 도오로",
        "wineNameEng": "Fiume D'Oro",
        "wineType": "화이트",
        "winePrice": 4,
        "wineSweet": 1,
        "wineBody": 3,
        "wineVariety": "블렌드",
        "aroma1": "돌",
        "aroma2": "허브",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0149000/W0149704.jpg",
        "wineName": "제이 보이머 라인가우 리슬링",
        "wineNameEng": "J.Baumer Rheingau Riesling",
        "wineType": "화이트",
        "winePrice": 3,
        "wineSweet": 4,
        "wineBody": 3,
        "wineVariety": "리슬링",
        "aroma1": "돌",
        "aroma2": "사과",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0148000/W0148696.jpg",
        "wineName": "이스와인",
        "wineNameEng": "I'ss Wine",
        "wineType": "화이트",
        "winePrice": 2,
        "wineSweet": 5,
        "wineBody": 2,
        "wineVariety": "모스카텔",
        "aroma1": "레몬",
        "aroma2": "사과",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0171000/W0171597.png",
        "wineName": "스윙 쉬라즈",
        "wineNameEng": "Swing Shiraz",
        "wineType": "레드",
        "winePrice": 2,
        "wineSweet": 1,
        "wineBody": 4,
        "wineVariety": "시라/쉬라즈",
        "aroma1": "베리",
        "aroma2": "시나몬",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0143000/W0143809.jpg",
        "wineName": "뷰 마넨 레세르바 까베르네소비뇽",
        "wineNameEng": "Viu Manent Reserva Cabernet Sauvignon",
        "wineType": "레드",
        "winePrice": 3,
        "wineSweet": 1,
        "wineBody": 3,
        "wineVariety": "카베르네 소비뇽",
        "aroma1": "베리",
        "aroma2": "오크통",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0150000/W0150974.jpg",
        "wineName": "다다",
        "wineNameEng": "DADA",
        "wineType": "스파클링",
        "winePrice": 0,
        "wineSweet": 4,
        "wineBody": 2,
        "wineVariety": "소비뇽 블랑",
        "aroma1": "꽃",
        "aroma2": "사과",
        "aroma3": " "
    },
    {
        "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0167000/W0167488.png",
        "wineName": "1865 마스터 블렌드",
        "wineNameEng": "1865 Master Blend",
        "wineType": "레드",
        "winePrice": 10,
        "wineSweet": 1,
        "wineBody": 5,
        "wineVariety": "블렌디드",
        "aroma1": "베리",
        "aroma2": "시나몬",
        "aroma3": "오크통"
    }
]