export const special_wine = [
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0157000/T0157182_006.png",
      "wineName": "한 피노누아",
      "wineNameEng": "Hahn Pinot Noir",
      "wineType": "레드",
      "winePrice": 6,
      "wineSweet": 1,
      "wineBody": 2,
      "wineVariety": "피노 누아",
      "aroma1": "베리",
      "aroma2": "사과",
      "aroma3": "숙성"
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0140000/W0140585.jpg",
      "wineName": "발디비에소 스파클링 모스카토",
      "wineNameEng": "Valdivieso Sparkling Moscato",
      "wineType": "스파클링",
      "winePrice": 2,
      "wineSweet": 4,
      "wineBody": 3,
      "wineVariety": "모스카토",
      "aroma1": "사과",
      "aroma2": "숙성",
      "aroma3": "파인애플"
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0141000/W0141387.jpg",
      "wineName": "빌라 엠",
      "wineNameEng": "Villa M",
      "wineType": "화이트",
      "winePrice": 3,
      "wineSweet": 4,
      "wineBody": 2,
      "wineVariety": "모스카토",
      "aroma1": "파인애플",
      "aroma2": " ",
      "aroma3": " "
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0163000/W0163836.jpg",
      "wineName": "투유",
      "wineNameEng": "TO YOU",
      "wineType": "스파클링",
      "winePrice": 8,
      "wineSweet": 3,
      "wineBody": 3,
      "wineVariety": "람브루스코",
      "aroma1": "베리",
      "aroma2": " ",
      "aroma3": " "
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0168000/W0168328.png",
      "wineName": "파운",
      "wineNameEng": "Faune",
      "wineType": "화이트",
      "winePrice": 5,
      "wineSweet": 1,
      "wineBody": 3,
      "wineVariety": "블렌디드",
      "aroma1": "꽃",
      "aroma2": "돌",
      "aroma3": "사과"
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0154000/T0154518_001.jpg",
      "wineName": "쿠수마노 인졸리아",
      "wineNameEng": "Cusumano Insolia",
      "wineType": "화이트",
      "winePrice": 3,
      "wineSweet": 1,
      "wineBody": 2,
      "wineVariety": "인졸리아",
      "aroma1": "꽃",
      "aroma2": "레몬",
      "aroma3": " "
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0165000/W0165535.jpg",
      "wineName": "아트",
      "wineNameEng": "Art",
      "wineType": "레드",
      "winePrice": 9,
      "wineSweet": 1,
      "wineBody": 3,
      "wineVariety": "멘시아",
      "aroma1": "돌",
      "aroma2": " ",
      "aroma3": " "
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0168000/T0168760_002.png",
      "wineName": "버터넛 피노 누아",
      "wineNameEng": "Butternut Pinot Noir",
      "wineType": "레드",
      "winePrice": 8,
      "wineSweet": 1,
      "wineBody": 3,
      "wineVariety": "피노 누아",
      "aroma1": "베리",
      "aroma2": "시나몬",
      "aroma3": "오크통"
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0154000/T0154071_001.png",
      "wineName": "또스띠 핑크 모스카토",
      "wineNameEng": "Tosti Pink Moscato",
      "wineType": "스파클링",
      "winePrice": 2,
      "wineSweet": 4,
      "wineBody": 3,
      "wineVariety": "블렌디드",
      "aroma1": "꽃",
      "aroma2": "베리",
      "aroma3": " "
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0148000/W0148696.jpg",
      "wineName": "이스와인",
      "wineNameEng": "I'ss Wine",
      "wineType": "화이트",
      "winePrice": 2,
      "wineSweet": 5,
      "wineBody": 2,
      "wineVariety": "모스카텔",
      "aroma1": "레몬",
      "aroma2": "사과",
      "aroma3": " "
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0142000/T0142219_003.png",
      "wineName": "타라파카 그란 레세르바 까베르네 소비뇽",
      "wineNameEng": "Tarapaca Gran Reserva Cabernet Sauvignon",
      "wineType": "레드",
      "winePrice": 6,
      "wineSweet": 1,
      "wineBody": 4,
      "wineVariety": "카베르네 소비뇽",
      "aroma1": "베리",
      "aroma2": "사과",
      "aroma3": "시나몬"
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0139000/139852.jpg",
      "wineName": "닥터 루젠 리슬링",
      "wineNameEng": "Dr.Loosen Riesling",
      "wineType": "화이트",
      "winePrice": 4,
      "wineSweet": 3,
      "wineBody": 2,
      "wineVariety": "리슬링",
      "aroma1": "돌",
      "aroma2": "사과",
      "aroma3": " "
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0139000/W0139038.jpg",
      "wineName": "에스쿠도 로호",
      "wineNameEng": "Escudo Rojo",
      "wineType": "레드",
      "winePrice": 4,
      "wineSweet": 1,
      "wineBody": 4,
      "wineVariety": "블렌디드",
      "aroma1": "베리",
      "aroma2": "오크통",
      "aroma3": " "
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0140000/W0140169.jpg",
      "wineName": "빌라 욜란다 모스카토 다스티",
      "wineNameEng": "Villa Jolanda Moscato d'Asti",
      "wineType": "화이트",
      "winePrice": 3,
      "wineSweet": 4,
      "wineBody": 2,
      "wineVariety": "모스카토",
      "aroma1": "꽃",
      "aroma2": "레몬",
      "aroma3": "사과"
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0161000/W0161664.jpg",
      "wineName": "매누아 그리뇽 소비뇽 블랑",
      "wineNameEng": "Manoir Grignon Sauvignon Blanc",
      "wineType": "화이트",
      "winePrice": 2,
      "wineSweet": 1,
      "wineBody": 3,
      "wineVariety": "소비뇽 블랑",
      "aroma1": "꽃",
      "aroma2": "파인애플",
      "aroma3": "허브"
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0150000/W0150974.jpg",
      "wineName": "다다",
      "wineNameEng": "DADA",
      "wineType": "스파클링",
      "winePrice": 0,
      "wineSweet": 4,
      "wineBody": 2,
      "wineVariety": "소비뇽 블랑",
      "aroma1": "꽃",
      "aroma2": "사과",
      "aroma3": " "
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0137000/W0137502.png",
      "wineName": "발비 소프라니 아스티",
      "wineNameEng": "Balbi Soprani Asti",
      "wineType": "스파클링",
      "winePrice": 4,
      "wineSweet": 4,
      "wineBody": 2,
      "wineVariety": "모스카토",
      "aroma1": "꽃",
      "aroma2": "레몬",
      "aroma3": "사과"
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0154000/W0154020.jpg",
      "wineName": "간치아 모스카토 로제",
      "wineNameEng": "Gancia Moscato Rose",
      "wineType": "스파클링",
      "winePrice": 3,
      "wineSweet": 4,
      "wineBody": 2,
      "wineVariety": "블렌디드",
      "aroma1": "꽃",
      "aroma2": "레몬",
      "aroma3": "베리"
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158809.jpg",
      "wineName": "에스쿠도 로호 시라",
      "wineNameEng": "Escudo Rojo Syrah",
      "wineType": "레드",
      "winePrice": 4,
      "wineSweet": 1,
      "wineBody": 4,
      "wineVariety": "시라/쉬라즈",
      "aroma1": "시나몬",
      "aroma2": "오크통",
      "aroma3": " "
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0159000/W0159688.jpg",
      "wineName": "판티니 그랑 뀌베 로제 스와로브스키",
      "wineNameEng": "Fantini Gran Cuvee Rose Swarovski",
      "wineType": "스파클링",
      "winePrice": 7,
      "wineSweet": 1,
      "wineBody": 3,
      "wineVariety": "알리아니코",
      "aroma1": "베리",
      "aroma2": " ",
      "aroma3": " "
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0160000/W0160819.jpg",
      "wineName": "도스",
      "wineNameEng": "Dos",
      "wineType": "레드",
      "winePrice": 4,
      "wineSweet": 1,
      "wineBody": 4,
      "wineVariety": "블렌디드",
      "aroma1": "베리",
      "aroma2": "시나몬",
      "aroma3": " "
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0168000/T0168759_001.png",
      "wineName": "버터넛 샤도네이",
      "wineNameEng": "Butternut Chardonnay",
      "wineType": "화이트",
      "winePrice": 8,
      "wineSweet": 1,
      "wineBody": 4,
      "wineVariety": "샤르도네",
      "aroma1": "사과",
      "aroma2": "아몬드",
      "aroma3": "오크통"
  },
  {
      "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0143000/W0143809.jpg",
      "wineName": "뷰 마넨 레세르바 까베르네소비뇽",
      "wineNameEng": "Viu Manent Reserva Cabernet Sauvignon",
      "wineType": "레드",
      "winePrice": 3,
      "wineSweet": 1,
      "wineBody": 3,
      "wineVariety": "카베르네 소비뇽",
      "aroma1": "베리",
      "aroma2": "오크통",
      "aroma3": " "
  }
]