export const special_wine = {
    "11": [
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0149000/W0149862.jpg",
            "wineName": "모엣 샹동 임페리얼",
            "wineNameEng": "Moet & Chandon Imperial",
            "wineType": "스파클링",
            "winePrice": 7,
            "wineSweet": 1,
            "wineBody": 2,
            "wineVariety": "블렌디드",
            "aroma1": "레몬",
            "aroma2": "사과",
            "aroma3": "크로와상"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0140000/W0140796.jpg",
            "wineName": "이기갈 꼬뜨 뒤 론 루즈",
            "wineNameEng": "E. Guigal Cotes du Rhone Rouge",
            "wineType": "레드",
            "winePrice": 3,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "블렌디드",
            "aroma1": "베리",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0155000/W0155687.jpg",
            "wineName": "폼비스 런 샤르도네",
            "wineNameEng": "Formby's Run Chardonnay",
            "wineType": "화이트",
            "winePrice": 3,
            "wineSweet": 2,
            "wineBody": 3,
            "wineVariety": "샤르도네",
            "aroma1": "레몬",
            "aroma2": "사과",
            "aroma3": "파인애플"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0159000/W0159952.jpg",
            "wineName": "이기갈 지공다스",
            "wineNameEng": "E.Guigal Gigondas",
            "wineType": "레드",
            "winePrice": 6,
            "wineSweet": 1,
            "wineBody": 4,
            "wineVariety": "블렌디드",
            "aroma1": "시나몬",
            "aroma2": "오크통",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0156000/W0156715.jpg",
            "wineName": "코넌드럼 레드",
            "wineNameEng": "Conundrum Red",
            "wineType": "레드",
            "winePrice": 6,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "블렌디드",
            "aroma1": "꽃",
            "aroma2": "베리",
            "aroma3": "사과"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0159000/W0159782.jpg",
            "wineName": "운두라가 시바리스 까베르네 소비뇽",
            "wineNameEng": "Undurraga Sibaris Cabernet Sauvignon",
            "wineType": "레드",
            "winePrice": 2,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "카베르네 소비뇽",
            "aroma1": "오크통",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0156000/W0156744.jpg",
            "wineName": "덕혼 디코이 멀롯",
            "wineNameEng": "Duckhorn Decoy Merlot",
            "wineType": "레드",
            "winePrice": 9,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "블렌디드",
            "aroma1": "베리",
            "aroma2": "사과",
            "aroma3": "시나몬"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0159000/W0159883.jpg",
            "wineName": "뿌삐유",
            "wineNameEng": "Poupille",
            "wineType": "레드",
            "winePrice": 6,
            "wineSweet": 1,
            "wineBody": 4,
            "wineVariety": "메를로",
            "aroma1": "말린과일",
            "aroma2": "베리",
            "aroma3": "사과"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0165000/W0165535.jpg",
            "wineName": "아트",
            "wineNameEng": "Art",
            "wineType": "레드",
            "winePrice": 9,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "멘시아",
            "aroma1": "돌",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0162000/W0162120.jpg",
            "wineName": "지디 바이라 랑게 로쏘",
            "wineNameEng": "GD Vajra Langhe Rosso",
            "wineType": "레드",
            "winePrice": 2,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "블렌디드",
            "aroma1": "꽃",
            "aroma2": "사과",
            "aroma3": "시나몬"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0161000/W0161299.jpg",
            "wineName": "말보로 썬 소비뇽 블랑",
            "wineNameEng": "Marlborough Sun Sauvignon Blanc",
            "wineType": "화이트",
            "winePrice": 4,
            "wineSweet": 1,
            "wineBody": 2,
            "wineVariety": "소비뇽 블랑",
            "aroma1": "사과",
            "aroma2": "숙성",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0165000/W0165827.jpg",
            "wineName": "니콜라스 푸이야트 셀렉션 브뤼",
            "wineNameEng": "Nicolas Feuilatte Selection Brut",
            "wineType": "스파클링",
            "winePrice": 9,
            "wineSweet": 1,
            "wineBody": 2,
            "wineVariety": "블렌디드",
            "aroma1": "사과",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0163000/W0163310.jpg",
            "wineName": "콜리올 피아노",
            "wineNameEng": "Coriole Fiano",
            "wineType": "화이트",
            "winePrice": 7,
            "wineSweet": 1,
            "wineBody": 2,
            "wineVariety": "피아노",
            "aroma1": "사과",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0151000/T0151381_001.png",
            "wineName": "로스 바스코스 로제",
            "wineNameEng": "Los Vascos Rose",
            "wineType": "로제",
            "winePrice": 2,
            "wineSweet": 2,
            "wineBody": 3,
            "wineVariety": "블렌디드",
            "aroma1": "레몬",
            "aroma2": "베리",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0162000/T0162697_002.png",
            "wineName": "까스따뇨 로제 세미 스위트",
            "wineNameEng": "Castano Rose Semi Sweet",
            "wineType": "로제",
            "winePrice": 3,
            "wineSweet": 3,
            "wineBody": 2,
            "wineVariety": "모나스트렐",
            "aroma1": "베리",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0148000/W0148696.jpg",
            "wineName": "이스와인",
            "wineNameEng": "I'ss Wine",
            "wineType": "화이트",
            "winePrice": 2,
            "wineSweet": 5,
            "wineBody": 2,
            "wineVariety": "모스카텔",
            "aroma1": "레몬",
            "aroma2": "사과",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0138000/W0138189.jpg",
            "wineName": "루이 자도 샤블리",
            "wineNameEng": "Louis Jadot Chablis",
            "wineType": "화이트",
            "winePrice": 4,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "샤르도네",
            "aroma1": "오크통",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158392.jpg",
            "wineName": "몬테스 클래식 샤도네이",
            "wineNameEng": "Montes Classic Chardonnay",
            "wineType": "화이트",
            "winePrice": 2,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "샤르도네",
            "aroma1": "시나몬",
            "aroma2": "파인애플",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0156000/W0156456.jpg",
            "wineName": "라 셰또 장 발몽 샤르도네",
            "wineNameEng": "La Cheteau Jean Balmont Chardonnay",
            "wineType": "화이트",
            "winePrice": 3,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "샤르도네",
            "aroma1": "레몬",
            "aroma2": "파인애플",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0168000/W0168328.png",
            "wineName": "파운",
            "wineNameEng": "Faune",
            "wineType": "화이트",
            "winePrice": 5,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "블렌디드",
            "aroma1": "꽃",
            "aroma2": "돌",
            "aroma3": "사과"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0153000/W0153507.jpg",
            "wineName": "샤또 데스클랑",
            "wineNameEng": "Chateau d'Esclans",
            "wineType": "로제",
            "winePrice": 8,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "블렌디드",
            "aroma1": "레몬",
            "aroma2": "베리",
            "aroma3": "사과"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0154000/W0154020.jpg",
            "wineName": "간치아 모스카토 로제",
            "wineNameEng": "Gancia Moscato Rose",
            "wineType": "스파클링",
            "winePrice": 3,
            "wineSweet": 4,
            "wineBody": 2,
            "wineVariety": "블렌디드",
            "aroma1": "꽃",
            "aroma2": "레몬",
            "aroma3": "베리"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0149000/T0149589_001.png",
            "wineName": "G7 까베르네 소비뇽",
            "wineNameEng": "G7 Cabernet Sauvignon",
            "wineType": "레드",
            "winePrice": 0,
            "wineSweet": 1,
            "wineBody": 2,
            "wineVariety": "카베르네 소비뇽",
            "aroma1": "베리",
            "aroma2": "오크통",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0150000/W0150974.jpg",
            "wineName": "다다",
            "wineNameEng": "DADA",
            "wineType": "스파클링",
            "winePrice": 0,
            "wineSweet": 4,
            "wineBody": 2,
            "wineVariety": "소비뇽 블랑",
            "aroma1": "꽃",
            "aroma2": "사과",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0147000/W0147941.jpg",
            "wineName": "샤또 깔롱",
            "wineNameEng": "Chateau Calon",
            "wineType": "레드",
            "winePrice": 7,
            "wineSweet": 1,
            "wineBody": 4,
            "wineVariety": "블렌디드",
            "aroma1": "숙성",
            "aroma2": "오크통",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0162000/W0162193.jpg",
            "wineName": "르 세드르",
            "wineNameEng": "Le Cedre",
            "wineType": "레드",
            "winePrice": 10,
            "wineSweet": 1,
            "wineBody": 5,
            "wineVariety": "말벡",
            "aroma1": "꽃",
            "aroma2": "돌",
            "aroma3": "사과"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0151000/W0151911.jpg",
            "wineName": "아이러브 모스카토",
            "wineNameEng": "I Love Moscato",
            "wineType": "화이트",
            "winePrice": 1,
            "wineSweet": 4,
            "wineBody": 1,
            "wineVariety": "모스카토",
            "aroma1": "파인애플",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0156000/T0156989_010.png",
            "wineName": "몬테스 알파 샤도네이",
            "wineNameEng": "Montes Alpha Chardonnay",
            "wineType": "화이트",
            "winePrice": 4,
            "wineSweet": 1,
            "wineBody": 4,
            "wineVariety": "샤르도네",
            "aroma1": "사과",
            "aroma2": "오크통",
            "aroma3": "파인애플"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0161000/W0161301.png",
            "wineName": "빌라 욜란다 모스카토 로제",
            "wineNameEng": "Villa Jolanda Moscato Rose",
            "wineType": "스파클링",
            "winePrice": 3,
            "wineSweet": 4,
            "wineBody": 3,
            "wineVariety": "블렌디드",
            "aroma1": "말린과일",
            "aroma2": "베리",
            "aroma3": "사과"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0145000/W0145331.jpg",
            "wineName": "도그 포인트 소비뇽 블랑",
            "wineNameEng": "Dog Point Sauvignon Blanc",
            "wineType": "화이트",
            "winePrice": 7,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "소비뇽 블랑",
            "aroma1": "레몬",
            "aroma2": "사과",
            "aroma3": "파인애플"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0171000/T0171297_001.png",
            "wineName": "샤토 부에라 르카치텔리",
            "wineNameEng": "Chateau Buera Rkatsiteli",
            "wineType": "화이트",
            "winePrice": 5,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "리켓사이텔리",
            "aroma1": "사과",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0140000/W0140169.jpg",
            "wineName": "빌라 욜란다 모스카토 다스티",
            "wineNameEng": "Villa Jolanda Moscato d'Asti",
            "wineType": "화이트",
            "winePrice": 3,
            "wineSweet": 4,
            "wineBody": 2,
            "wineVariety": "모스카토",
            "aroma1": "꽃",
            "aroma2": "레몬",
            "aroma3": "사과"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0139000/W0139038.jpg",
            "wineName": "에스쿠도 로호",
            "wineNameEng": "Escudo Rojo",
            "wineType": "레드",
            "winePrice": 4,
            "wineSweet": 1,
            "wineBody": 4,
            "wineVariety": "블렌디드",
            "aroma1": "베리",
            "aroma2": "오크통",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0147000/W0147907.jpg",
            "wineName": "클라우디 베이 피노 누아",
            "wineNameEng": "Cloudy Bay Pinot Noir",
            "wineType": "레드",
            "winePrice": 6,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "피노 누아",
            "aroma1": "베리",
            "aroma2": "숙성",
            "aroma3": "시나몬"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158537.jpg",
            "wineName": "미래",
            "wineNameEng": "Mirre",
            "wineType": "레드",
            "winePrice": 8,
            "wineSweet": 1,
            "wineBody": 4,
            "wineVariety": "네그로아마로",
            "aroma1": "베리",
            "aroma2": "사과",
            "aroma3": "숙성"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0162000/W0162192.jpg",
            "wineName": "샤또 뒤 세드르",
            "wineNameEng": "Chateau du Cedre",
            "wineType": "레드",
            "winePrice": 5,
            "wineSweet": 1,
            "wineBody": 4,
            "wineVariety": "블렌디드",
            "aroma1": "꽃",
            "aroma2": "사과",
            "aroma3": "오크통"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0150000/W0150738.jpg",
            "wineName": "덕혼 디코이 샤도네이",
            "wineNameEng": "Duckhorn Decoy Chardonnay",
            "wineType": "화이트",
            "winePrice": 7,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "샤르도네",
            "aroma1": "꽃",
            "aroma2": "돌",
            "aroma3": "레몬"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158375.jpg",
            "wineName": "프레스코발디 레몰레 로쏘",
            "wineNameEng": "Frescobaldi Remole Rosso",
            "wineType": "레드",
            "winePrice": 2,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "블렌디드",
            "aroma1": "베리",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0154000/154481.jpg",
            "wineName": "루이 자도 부르고뉴 피노누아",
            "wineNameEng": "Louis Jadot Bourgogne Pinot Noir",
            "wineType": "레드",
            "winePrice": 3,
            "wineSweet": 1,
            "wineBody": 2,
            "wineVariety": "피노 누아",
            "aroma1": "사과",
            "aroma2": "오크통",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0170000/W0170200.png",
            "wineName": "알루아도 알리칸테 부쉐",
            "wineNameEng": "Aluado Alicante Bouschet",
            "wineType": "레드",
            "winePrice": 4,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "알리칸테 부쉐",
            "aroma1": "사과",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0139000/139852.jpg",
            "wineName": "닥터 루젠 리슬링",
            "wineNameEng": "Dr.Loosen Riesling",
            "wineType": "화이트",
            "winePrice": 4,
            "wineSweet": 3,
            "wineBody": 2,
            "wineVariety": "리슬링",
            "aroma1": "돌",
            "aroma2": "사과",
            "aroma3": " "
        }
    ],
    "12": [
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0160000/T0160904_003.jpg",
            "wineName": "산타 클로스 드 토리바스 크리안자",
            "wineNameEng": "Santa Clos de Torribas Crianza",
            "wineType": "레드",
            "winePrice": 4,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "템프라니요",
            "aroma1": "오크통",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0167000/W0167099.png",
            "wineName": "체라수올로 다브루쪼",
            "wineNameEng": "Cerasuolo d'Aburzzo",
            "wineType": "로제",
            "winePrice": 5,
            "wineSweet": 1,
            "wineBody": 2,
            "wineVariety": "몬테풀치아노",
            "aroma1": "베리",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0151000/W0151001.jpg",
            "wineName": "모젤 크리스마스 리슬링",
            "wineNameEng": "Mosel Christmas Riesling",
            "wineType": "화이트",
            "winePrice": 5,
            "wineSweet": 3,
            "wineBody": 2,
            "wineVariety": "리슬링",
            "aroma1": "사과",
            "aroma2": "레몬",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0151000/W0151002.jpg",
            "wineName": "모젤 크리스마스 로제",
            "wineNameEng": "Mosel Christmas Rose",
            "wineType": "로제",
            "winePrice": 5,
            "wineSweet": 3,
            "wineBody": 2,
            "wineVariety": "슈페트부르군더",
            "aroma1": "사과",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0149000/W0149862.jpg",
            "wineName": "모엣 샹동 임페리얼",
            "wineNameEng": "Moet & Chandon Imperial",
            "wineType": "스파클링",
            "winePrice": 7,
            "wineSweet": 1,
            "wineBody": 2,
            "wineVariety": "블렌디드",
            "aroma1": "사과",
            "aroma2": "레몬",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0166000/W0166466.jpg",
            "wineName": "클라랑델 앰버",
            "wineNameEng": "Clarendelle Amber",
            "wineType": "화이트",
            "winePrice": 9,
            "wineSweet": 5,
            "wineBody": 5,
            "wineVariety": "블렌디드",
            "aroma1": "사과",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0167000/W0167964.png",
            "wineName": "크리스마스 아스티",
            "wineNameEng": "Christmas Asti",
            "wineType": "스파클링",
            "winePrice": 3,
            "wineSweet": 4,
            "wineBody": 2,
            "wineVariety": "모스카토",
            "aroma1": "레몬",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0157000/T0157182_006.png",
            "wineName": "한 피노누아",
            "wineNameEng": "Hahn Pinot Noir",
            "wineType": "레드",
            "winePrice": 6,
            "wineSweet": 1,
            "wineBody": 2,
            "wineVariety": "피노 누아",
            "aroma1": "베리",
            "aroma2": "사과",
            "aroma3": "숙성"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0140000/W0140585.jpg",
            "wineName": "발디비에소 스파클링 모스카토",
            "wineNameEng": "Valdivieso Sparkling Moscato",
            "wineType": "스파클링",
            "winePrice": 2,
            "wineSweet": 4,
            "wineBody": 3,
            "wineVariety": "모스카토",
            "aroma1": "사과",
            "aroma2": "숙성",
            "aroma3": "파인애플"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0141000/W0141387.jpg",
            "wineName": "빌라 엠",
            "wineNameEng": "Villa M",
            "wineType": "화이트",
            "winePrice": 3,
            "wineSweet": 4,
            "wineBody": 2,
            "wineVariety": "모스카토",
            "aroma1": "파인애플",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0168000/W0168328.png",
            "wineName": "파운",
            "wineNameEng": "Faune",
            "wineType": "화이트",
            "winePrice": 5,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "블렌디드",
            "aroma1": "꽃",
            "aroma2": "돌",
            "aroma3": "사과"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0154000/T0154518_001.jpg",
            "wineName": "쿠수마노 인졸리아",
            "wineNameEng": "Cusumano Insolia",
            "wineType": "화이트",
            "winePrice": 3,
            "wineSweet": 1,
            "wineBody": 2,
            "wineVariety": "인졸리아",
            "aroma1": "꽃",
            "aroma2": "레몬",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0165000/W0165535.jpg",
            "wineName": "아트",
            "wineNameEng": "Art",
            "wineType": "레드",
            "winePrice": 9,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "멘시아",
            "aroma1": "돌",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0168000/T0168760_002.png",
            "wineName": "버터넛 피노 누아",
            "wineNameEng": "Butternut Pinot Noir",
            "wineType": "레드",
            "winePrice": 8,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "피노 누아",
            "aroma1": "베리",
            "aroma2": "시나몬",
            "aroma3": "오크통"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0148000/W0148696.jpg",
            "wineName": "이스와인",
            "wineNameEng": "I'ss Wine",
            "wineType": "화이트",
            "winePrice": 2,
            "wineSweet": 5,
            "wineBody": 2,
            "wineVariety": "모스카텔",
            "aroma1": "레몬",
            "aroma2": "사과",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0139000/139852.jpg",
            "wineName": "닥터 루젠 리슬링",
            "wineNameEng": "Dr.Loosen Riesling",
            "wineType": "화이트",
            "winePrice": 4,
            "wineSweet": 3,
            "wineBody": 2,
            "wineVariety": "리슬링",
            "aroma1": "돌",
            "aroma2": "사과",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0139000/W0139038.jpg",
            "wineName": "에스쿠도 로호",
            "wineNameEng": "Escudo Rojo",
            "wineType": "레드",
            "winePrice": 4,
            "wineSweet": 1,
            "wineBody": 4,
            "wineVariety": "블렌디드",
            "aroma1": "베리",
            "aroma2": "오크통",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0140000/W0140169.jpg",
            "wineName": "빌라 욜란다 모스카토 다스티",
            "wineNameEng": "Villa Jolanda Moscato d'Asti",
            "wineType": "화이트",
            "winePrice": 3,
            "wineSweet": 4,
            "wineBody": 2,
            "wineVariety": "모스카토",
            "aroma1": "꽃",
            "aroma2": "레몬",
            "aroma3": "사과"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0161000/W0161664.jpg",
            "wineName": "매누아 그리뇽 소비뇽 블랑",
            "wineNameEng": "Manoir Grignon Sauvignon Blanc",
            "wineType": "화이트",
            "winePrice": 2,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "소비뇽 블랑",
            "aroma1": "꽃",
            "aroma2": "파인애플",
            "aroma3": "허브"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0137000/W0137502.png",
            "wineName": "발비 소프라니 아스티",
            "wineNameEng": "Balbi Soprani Asti",
            "wineType": "스파클링",
            "winePrice": 4,
            "wineSweet": 4,
            "wineBody": 2,
            "wineVariety": "모스카토",
            "aroma1": "꽃",
            "aroma2": "레몬",
            "aroma3": "사과"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0154000/W0154020.jpg",
            "wineName": "간치아 모스카토 로제",
            "wineNameEng": "Gancia Moscato Rose",
            "wineType": "스파클링",
            "winePrice": 3,
            "wineSweet": 4,
            "wineBody": 2,
            "wineVariety": "블렌디드",
            "aroma1": "꽃",
            "aroma2": "레몬",
            "aroma3": "베리"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158809.jpg",
            "wineName": "에스쿠도 로호 시라",
            "wineNameEng": "Escudo Rojo Syrah",
            "wineType": "레드",
            "winePrice": 4,
            "wineSweet": 1,
            "wineBody": 4,
            "wineVariety": "시라/쉬라즈",
            "aroma1": "시나몬",
            "aroma2": "오크통",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0159000/W0159688.jpg",
            "wineName": "판티니 그랑 뀌베 로제 스와로브스키",
            "wineNameEng": "Fantini Gran Cuvee Rose Swarovski",
            "wineType": "스파클링",
            "winePrice": 7,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "알리아니코",
            "aroma1": "베리",
            "aroma2": " ",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0160000/W0160819.jpg",
            "wineName": "도스",
            "wineNameEng": "Dos",
            "wineType": "레드",
            "winePrice": 4,
            "wineSweet": 1,
            "wineBody": 4,
            "wineVariety": "블렌디드",
            "aroma1": "베리",
            "aroma2": "시나몬",
            "aroma3": " "
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/IMAGE/0168000/T0168759_001.png",
            "wineName": "버터넛 샤도네이",
            "wineNameEng": "Butternut Chardonnay",
            "wineType": "화이트",
            "winePrice": 8,
            "wineSweet": 1,
            "wineBody": 4,
            "wineVariety": "샤르도네",
            "aroma1": "사과",
            "aroma2": "아몬드",
            "aroma3": "오크통"
        },
        {
            "wineImage": "https://wine21.speedgabia.com/WINE_MST/TITLE/0143000/W0143809.jpg",
            "wineName": "뷰 마넨 레세르바 까베르네소비뇽",
            "wineNameEng": "Viu Manent Reserva Cabernet Sauvignon",
            "wineType": "레드",
            "winePrice": 3,
            "wineSweet": 1,
            "wineBody": 3,
            "wineVariety": "카베르네 소비뇽",
            "aroma1": "베리",
            "aroma2": "오크통",
            "aroma3": " "
        }
    ]
}