export const wine_test_data = [
  {
    wineCode: "1111",
    wineImage:
      "https://wine21.speedgabia.com/WINE_MST/TITLE/0159000/W0159028.jpg",
    wineName: "오이스터 베이 소비뇽 블랑",
    wineNameEng: "Oyster Bay Sauvignon Blanc",
    wineType: "화이트",
    wineAlcohol: "13",
    winePrice: 3,
    wineSweet: 1,
    wineBody: 2,
    wineVariety: "소비뇽 블랑",
    aroma1: "미네랄",
    aroma2: "사과",
    aroma3: " ",
    wineText:
      "집에서 혼자 마시는 와인이 좋은 이유는 상대와 속도를 맞춰 마시지 않아도 되고, 마음대로 집어먹을 수 있는 안주가 있고, 언제든 취해 드러누울 수 있는 침대가 있기 때문. 그러니까 이 한 병을 비울 때만큼은 그 무엇이든지 내 마음대로 해도 되기 때문이다. 한 잔씩 잔이 채워지고 병을 비워갈 때쯤엔 아까 기분이 어땠는지 지나간 마음이 어땠는지 조금도 생각나지 않을 것이다. 기분이 좀 그렇다면, 재밌는 넷플릭스를 틀어두고 화이트 와인 한 병 어떨까?",
  },
  {
    wineCode: "1112",
    wineImage:
      "https://wine21.speedgabia.com/WINE_MST/TITLE/0158000/W0158106.jpg",
    wineName: "샤또 샤스 스플린",
    wineNameEng: "Chateau Chasse Spleen",
    wineType: "레드",
    wineAlcohol: "12 - 13",
    winePrice: 8,
    wineSweet: 1,
    wineBody: 4,
    wineVariety: "블렌디드",
    aroma1: " ",
    aroma2: " ",
    aroma3: " ",
    wineText:
      "'슬픔이란 안녕'이라는 뜻의 '샤스 스플린(Chasse Spleen)'은 프랑스 보르도(Bordeaux)의 물리(Moulis) 지역에서 생산한 레드 와인입니다. 프랑스의 유명한 시인 샤를 보들레르(Charles Baudelaire)가 사랑한 와인으로도 잘 알려져 있는데요. 실제로 보들레르는 이 와인을 마시며 슬픔을 달랬다고 해요.",
  },
  {
    wineCode: "1211",
    wineImage:
      "https://wine21.speedgabia.com/WINE_MST/TITLE/0172000/W0172246.png",
    wineName: "낙낙 레드 블랜드",
    wineNameEng: "Knock Knock Red Blend",
    wineType: "레드",
    wineAlcohol: "12 - 13",
    winePrice: 2,
    wineSweet: 1,
    wineBody: 4,
    wineVariety: "블렌디드",
    aroma1: "오크통",
    aroma2: " ",
    aroma3: " ",
    wineText: "부담없는 스타일과 뛰어난 접근성을 가진 낙낙 레드 블랜드",
  },
  {
    wineCode: "1221",
    wineImage:
      "https://wine21.speedgabia.com/WINE_MST/TITLE/0162000/W0162076.jpg",
    wineName: "피치니, 메모로 로사토",
    wineNameEng: "Piccini, Memoro Rosato",
    wineType: "로제",
    wineAlcohol: "13 - 14",
    winePrice: 0,
    wineSweet: 2,
    wineBody: 2,
    wineVariety: "블렌디드",
    aroma1: "베리",
    aroma2: "허브",
    aroma3: " ",
    wineText:
      "이태리 통일 150주년을 기념해 출시한 와인이다. 이태리 동서남북 각각의 지역을 대표하는 포도품종 4가지가 블렌딩 되어있어 더욱 풍부한 맛을 즐길 수 있다. 딸기와 라즈베리, 붉은 체리의 신선한 맛이 살아있지만 산미도 적당하고, 은근한 바디감도 느껴지는 조화로운 맛이다. 가격대가 다른 와인에 비해서 조금 있는 편이지만, 데일리로 즐기기에 좋은 와인으로 평가 받고 있다. 예쁜 병 디자인에 와인 오프너도 필요 없으니 자취러에게 강력 추천!",
  },
  {
    wineCode: "1321",
    wineImage:
      "https://wine21.speedgabia.com/WINE_MST/TITLE/0169000/W0169886.png",
    wineName: "무똥 까데, 블랑",
    wineNameEng: "Mouton Cadet, Blanc",
    wineType: "화이트",
    wineAlcohol: "13 - 14",
    winePrice: 2,
    wineSweet: 1,
    wineBody: 2,
    wineVariety: "블렌디드",
    aroma1: "사과",
    aroma2: "꽃",
    aroma3: "레몬",
    wineText:
      "퇴근 후 가볍게 화이트 와인 한 잔 어때 ? 전세계 판매 1위 보르도 와인 무똥까데 브랜드의 베스트 셀링 와인으로 와린이도 쉽게 즐길 수 있는 데일리 화이트 와인",
  },
  {
    wineCode: "1411",
    wineImage:
      "https://wine21.speedgabia.com/WINE_MST/TITLE/0167000/W0167526.png",
    wineName: "빌라 욜란다 모스카토 다스티",
    wineNameEng: "Villa Jolanda Moscato d'Asti 'Black Edition'",
    wineType: "화이트",
    wineAlcohol: "7",
    winePrice: 1,
    wineSweet: 3,
    wineBody: 2,
    wineVariety: "모스카토",
    aroma1: "꽃",
    aroma2: "레몬",
    aroma3: "사과",
    wineText:
      "모스카토의 풍성한 향은 하루의 피로를 설렘으로 바꾼다. 복숭아와 살구, 머스캣의 선명한 과일 향에 더해진 산미는 타르트나 케이크와 같은 디저트와 궁합이 좋다. 조밀한 기포와 함께 퍼지는 우아한 풍미는 나를 위한 선물을 준비하고 싶은 밤 가장 먼저 생각난다.",
  },
  {
    wineCode: "1412",
    wineImage:
      "https://wine21.speedgabia.com/WINE_MST/TITLE/0169000/W0169974.png",
    wineName: "카르페네 말볼티, 1868 프로세코 수페리오레",
    wineNameEng: "Carpene Malvolti, 1868 Prosecco Superiore",
    wineType: "스파클링",
    wineAlcohol: "11 - 12",
    winePrice: 4,
    wineSweet: 1,
    wineBody: 2,
    wineVariety: "글레라",
    aroma1: "레몬",
    aroma2: "사과",
    aroma3: "오크통",
    wineText:
      "세계 최초로 프로세코 스파클링을 생산한 와이너리인 카르페네 말볼티의 프로세코 스파클링 와인 중 복합미와 과일향이 뛰어난 와인",
  },
  {
    wineCode: "2111",
    wineImage:
      "https://wine21.speedgabia.com/WINE_MST/TITLE/0137000/W0137400.jpg",
    wineName: "루피노, 리제르바 두칼레 끼안티 클라시코 리제르바",
    wineNameEng: "Ruffino, Riserva Ducale Chianti Classico Riserva",
    wineType: "레드",
    wineAlcohol: "13 - 14",
    winePrice: 7,
    wineSweet: 1,
    wineBody: 4,
    wineVariety: "블렌디드",
    aroma1: "베리",
    aroma2: "시나몬",
    aroma3: "오크통",
    wineText:
      "영화 <악마는 프라다를 입는다(2007)>. 잡지사를 다니는 주인공 '앤디(앤 해서웨이)'가 퇴근 후 남자친구와 함께 마시는 와인이 '루피노 리제르바 두칼레'입니다. 실제로 뉴욕에서 가장 많이 팔릴 만큼 뉴요커들이 사랑하는 와인으로 잘 알려져 있죠.",
  },
];
